test_that("normalize_citation matches the shared cases", {
  cases <- shared_fixture("citations")$normalize_citation$cases
  expect_gt(length(cases), 0)

  for (case in cases) {
    expect_identical(
      normalize_citation(case$input),
      case$expected,
      info = case$name
    )
  }
})

test_that("match_citation uses the shared minimum quote length", {
  # A quote shorter than this never verifies. Both packages read the limit from
  # the fixture so it cannot drift between them.
  minimum <- shared_fixture("citations")$match_citation$min_normalized_length
  entry <- list(label = "documentation", kind = "prose", text = strrep("x", minimum))

  expect_null(match_citation(strrep("x", minimum - 1), list(entry)))
  expect_identical(
    match_citation(strrep("x", minimum), list(entry)),
    list(label = "documentation", kind = "prose")
  )
})

test_that("match_citation matches the shared verdicts", {
  spec <- shared_fixture("citations")$match_citation
  expect_gt(length(spec$cases), 0)

  for (case in spec$cases) {
    corpus <- lapply(case$corpus, function(entry) {
      list(label = entry$label, kind = entry$kind, text = entry$text)
    })
    got <- match_citation(case$quote, corpus)
    if (is.null(case$expected)) {
      expect_null(got, info = case$name)
    } else {
      expect_identical(
        got,
        list(label = case$expected$label, kind = case$expected$kind),
        info = case$name
      )
    }
  }
})

test_that("citation asides blockquote every line of multiline evidence", {
  html <- citation_aside_html(
    "Canopy cover is always acre-weighted.\nReport acreage after filtering.",
    "This supports the weighting rule.",
    "forest documentation",
    "prose"
  )

  expect_match(
    html,
    "> Canopy cover is always acre-weighted.\n> Report acreage after filtering.",
    fixed = TRUE
  )
})

test_that("citation asides leave trust copy to their markers", {
  html <- citation_aside_html(
    "Canopy cover is always acre-weighted.",
    "This supports the weighting rule.",
    "forest documentation",
    "prose"
  )

  expect_no_match(
    html,
    "Quote matched exactly against trusted context. Explanation generated by AI.",
    fixed = TRUE
  )
})

test_that("corpus entries carry a kind and a reader-facing label", {
  skip_if_not_installed("yaml")
  doc <- withr::local_tempfile(fileext = ".md")
  writeLines("Fiscal year starts in February.", doc)
  path <- withr::local_tempfile(fileext = ".yaml")
  writeLines(
    c(
      '$version: "0.1.0"',
      "name: retail sales",
      "description: Order and revenue data for a small retailer.",
      "tables:",
      "  - name: sales",
      "    columns:",
      "      - name: revenue",
      "        description: Booked revenue, net of discounts."
    ),
    path
  )
  source <- data_source(sales = test_sales(), dictionary = path)

  corpus <- build_citation_corpus(
    augment_context_layer(context_layer(files = doc), list(source)),
    list(order_count = count_measure_tool()),
    list(sales_db = source)
  )

  expect_equal(
    match_citation("Fiscal year starts in February.", corpus),
    list(label = "documentation", kind = "prose")
  )
  expect_equal(
    match_citation(
      "Count orders, optionally filtered by region and a revenue ceiling.",
      corpus
    ),
    list(label = "order_count definition", kind = "definition")
  )
  expect_equal(
    match_citation("Booked revenue, net of discounts.", corpus),
    list(label = "sales table", kind = "schema")
  )
  expect_equal(
    match_citation("Order and revenue data for a small retailer.", corpus),
    list(label = "sales_db dictionary", kind = "schema")
  )
  expect_null(match_citation("tax", corpus))
})

test_that("the citation corpus spans context, measures, and dictionaries", {
  skip_if_not_installed("yaml")
  doc <- withr::local_tempfile(fileext = ".md")
  writeLines("Fiscal year starts in February.", doc)
  layer <- context_layer(files = doc)
  registry <- list(order_count = count_measure_tool())
  path <- withr::local_tempfile(fileext = ".yaml")
  writeLines(
    c(
      '$version: "0.1.0"',
      "name: retail sales",
      "tables:",
      "  - name: sales",
      "    description: One row per order line.",
      "    columns:",
      "      - name: revenue",
      "        description: Booked revenue, net of discounts."
    ),
    path
  )
  source <- data_source(sales = test_sales(), dictionary = path)

  corpus <- build_citation_corpus(
    augment_context_layer(layer, list(source)),
    registry,
    list(source)
  )

  expect_false(is.null(match_citation(
    "Fiscal year starts in February.",
    corpus
  )))
  expect_equal(
    match_citation(
      "Count orders, optionally filtered by region and a revenue ceiling.",
      corpus
    )$label,
    "order_count definition"
  )
  expect_equal(
    match_citation("Booked revenue, net of discounts.", corpus)$label,
    "sales table"
  )
})

test_that("dictionary prose keeps its specific label once it is also context", {
  skip_if_not_installed("yaml")
  path <- withr::local_tempfile(fileext = ".yaml")
  writeLines(
    c(
      '$version: "0.1.0"',
      "name: retail sales",
      "details: Revenue figures exclude tax collected at checkout.",
      "tables:",
      "  - name: sales",
      "    description: One row per order line.",
      "    details: Refunds appear as negative-revenue rows."
    ),
    path
  )
  source <- data_source(sales = test_sales(), dictionary = path)
  own_doc <- withr::local_tempfile(fileext = ".md")
  writeLines("Fiscal year starts in February.", own_doc)

  corpus <- build_citation_corpus(
    augment_context_layer(context_layer(files = own_doc), list(source)),
    list(),
    list(source)
  )

  expect_equal(
    match_citation("One row per order line.", corpus)$label,
    "sales table"
  )
  expect_equal(
    match_citation("Refunds appear as negative-revenue rows.", corpus)$label,
    "sales table"
  )
  expect_equal(
    match_citation(
      "Revenue figures exclude tax collected at checkout.",
      corpus
    )$label,
    "data dictionary"
  )
  expect_equal(
    match_citation("Fiscal year starts in February.", corpus)$label,
    "documentation"
  )
})

test_that("corpus measure text matches multi-source presentation", {
  registry <- list(
    region_revenue = measure(
      "region_revenue",
      "Total revenue for a region.",
      function(region, sales_db) NULL,
      arguments = list(region = ellmer::type_string("The sales region."))
    )
  )
  sources <- list(sales_db = test_source(), crm = test_source())

  corpus <- build_citation_corpus(NULL, registry, sources)

  # search_pool presents a `sources:` line to multi-source agents; a
  # verbatim quote spanning it must verify.
  expect_equal(
    match_citation(
      "Total revenue for a region.\n\nsources: sales_db",
      corpus
    )$label,
    "region_revenue definition"
  )
})

test_that("dataset-level dictionary prose is citable", {
  skip_if_not_installed("yaml")
  path <- withr::local_tempfile(fileext = ".yaml")
  writeLines(
    c(
      '$version: "0.1.0"',
      "name: retail sales",
      "description: Order and revenue data for a small retailer.",
      "details: Revenue figures exclude tax collected at checkout."
    ),
    path
  )
  source <- data_source(sales = test_sales(), dictionary = path)

  corpus <- build_citation_corpus(NULL, list(), list(source))

  expect_equal(
    match_citation(
      "Order and revenue data for a small retailer.",
      corpus
    )$label,
    "data dictionary"
  )
  expect_equal(
    match_citation(
      "Revenue figures exclude tax collected at checkout.",
      corpus
    )$label,
    "data dictionary"
  )
})

test_that("add_citation_request appends one reminder per user turn", {
  tracker <- new.env(parent = emptyenv())
  tracker$reminder <- "SHORT CITATION REMINDER"
  first <- tool_result("6 rows", title = "Ran SQL", tag = "B")
  second <- tool_result("3 rows", title = "Ran SQL", tag = "B")
  third <- tool_result("2 rows", title = "Ran SQL", tag = "B")

  first <- add_citation_request(first, tracker)
  second <- add_citation_request(second, tracker)
  tracker$requested <- FALSE
  third <- add_citation_request(third, tracker)

  expect_match(first@value, "6 rows")
  expect_match(first@value, "SHORT CITATION REMINDER", fixed = TRUE)
  expect_equal(second@value, "3 rows")
  expect_match(third@value, "SHORT CITATION REMINDER", fixed = TRUE)
})

test_that("add_citation_request appends ContentText to content lists", {
  tracker <- new.env(parent = emptyenv())
  result <- tool_result(
    list(ellmer::ContentText(text = "output")),
    title = "Ran R code",
    tag = "B"
  )

  result <- add_citation_request(result, tracker)

  expect_length(result@value, 2)
  expect_match(result@value[[2]]@text, "<commons-citation>", fixed = TRUE)
})

test_that("search_context requests a citation for fallback answers", {
  path <- withr::local_tempfile(fileext = ".md")
  writeLines(
    "Regeneration units are tracked separately until they close canopy.",
    path
  )
  agent <- test_agent(context_layer = context_layer(files = path))

  result <- agent_tool(agent, "search_context")(
    query = "regeneration baseline"
  )

  expect_s7_class(result, ellmer::ContentToolResult)
  expect_match(result@value, "<commons-citation>", fixed = TRUE)
})

test_that("citation_reminder_text names the commons-citation dialect", {
  reminder <- citation_reminder_text()

  expect_match(reminder, "<commons-citation>", fixed = TRUE)
  expect_no_match(reminder, "<citation reason", fixed = TRUE)
})

test_that("citation requests do not prescribe answer length", {
  request <- test_agent()$get_system_prompt()

  expect_no_match(request, "paragraph", fixed = TRUE)
})

test_that("citation instructions describe only available tool outputs", {
  base <- test_agent()$get_system_prompt()
  expect_match(base, "<commons-citation>", fixed = TRUE)
  expect_match(base, "From `search_context`", fixed = TRUE)
  expect_match(base, "From `describe_table`", fixed = TRUE)
  expect_match(base, "From `run_sql`", fixed = TRUE)
  expect_match(base, "output from `run_r`", fixed = TRUE)
  expect_no_match(base, "`search_pool`", fixed = TRUE)
  expect_no_match(base, "`call_measure`", fixed = TRUE)
  expect_no_match(base, "`call_metrics`", fixed = TRUE)

  with_measures <- test_agent(
    semantic_layer = semantic_layer(count_measure_tool())
  )$get_system_prompt()
  expect_match(with_measures, "From `search_pool`", fixed = TRUE)
  expect_match(with_measures, "Result values from `call_measure`", fixed = TRUE)
  expect_no_match(with_measures, "`call_metrics`", fixed = TRUE)
  expect_no_match(with_measures, "Native semantic-model", fixed = TRUE)
})

test_that("citation trust exception names trusted calculation tools", {
  expect_equal(citation_trust_exception(character()), "")
  expect_equal(
    citation_trust_exception("call_measure"),
    " that is not based solely on output from `call_measure`"
  )
  expect_equal(
    citation_trust_exception("call_calculation"),
    " that is not based solely on output from `call_calculation`"
  )
  expect_equal(
    citation_trust_exception(
      c("search_pool", "call_measure", "call_metrics")
    ),
    paste0(
      " that is not based solely on output from `search_pool`",
      " or `call_measure`",
      " or `call_metrics`"
    )
  )
  expect_match(
    non_citable_tool_output_text("call_calculation"),
    "Result values from `call_calculation`",
    fixed = TRUE
  )
})

test_that("user messages reset citation requests but tool results do not", {
  agent <- test_agent()
  tracker <- agent$.__enclos_env__$private$citation_request
  tracker$requested <- TRUE

  agent$add_turn(
    ellmer::UserTurn("How many orders are there?"),
    ellmer::AssistantTurn("I'll check."),
    log_tokens = FALSE
  )
  expect_false(tracker$requested)

  tracker$requested <- TRUE
  agent$add_turn(
    ellmer::UserTurn(list(tool_result("6 rows", title = "Ran SQL", tag = "B"))),
    ellmer::AssistantTurn("There are 6 orders."),
    log_tokens = FALSE
  )
  expect_true(tracker$requested)
})

test_that("render_citation_aside emits a numbered aside with source details", {
  corpus <- list(list(
    label = "sales table",
    kind = "schema",
    text = "Revenue is recognized at shipment, not at order placement."
  ))
  out <- render_citation_aside(
    "Revenue is recognized at shipment, not at order placement.",
    "The computation follows the documented recognition rule.",
    corpus
  )
  expect_match(
    out$html,
    paste0(
      '^<shiny-aside display="compact" label="sales table" ',
      'icon="commons-icons/citation-schema.svg'
    )
  )
  expect_no_match(out$html, "data:image", fixed = TRUE)
  expect_match(
    out$html,
    "The computation follows the documented recognition rule.",
    fixed = TRUE
  )
  expect_match(out$html, "> Revenue is recognized at shipment", fixed = TRUE)
  expect_no_match(
    out$html,
    "Quote matched exactly against trusted context. Explanation generated by AI.",
    fixed = TRUE
  )
  expect_identical(out$decision$status, "accepted")
})

test_that("render_citation_aside emits nothing for an unverified quote", {
  out <- render_citation_aside("Nobody ever wrote this.", "reason", list())
  expect_identical(out$html, "")
  expect_identical(out$decision$status, "rejected")
})

test_that("unknown citation kinds have no icon", {
  expect_null(citation_icon_url("unknown"))
  expect_null(commons_icon_url("missing.svg"))
})
