test_that("normalize_citation matches the shared cases", {
  cases <- shared_fixture("citations")$normalize_citation$cases
  expect_gt(length(cases), 0)

  for (case in cases) {
    expect_identical(
      normalize_citation(case$input),
      case$expected,
      info = case$name
    )
  }
})

test_that("match_citation uses the shared minimum quote length", {
  # A quote shorter than this never verifies. Both packages read the limit from
  # the fixture so it cannot drift between them.
  minimum <- shared_fixture("citations")$match_citation$min_normalized_length
  entry <- list(label = "documentation", kind = "prose", text = strrep("x", minimum))

  expect_null(match_citation(strrep("x", minimum - 1), list(entry)))
  expect_identical(
    match_citation(strrep("x", minimum), list(entry)),
    list(label = "documentation", kind = "prose")
  )
})

test_that("match_citation matches the shared verdicts", {
  spec <- shared_fixture("citations")$match_citation
  expect_gt(length(spec$cases), 0)

  for (case in spec$cases) {
    corpus <- lapply(case$corpus, function(entry) {
      list(label = entry$label, kind = entry$kind, text = entry$text)
    })
    got <- match_citation(case$quote, corpus)
    if (is.null(case$expected)) {
      expect_null(got, info = case$name)
    } else {
      expect_identical(
        got,
        list(label = case$expected$label, kind = case$expected$kind),
        info = case$name
      )
    }
  }
})

test_that("citation asides blockquote every line of multiline evidence", {
  html <- citation_aside_html(
    "Canopy cover is always acre-weighted.\nReport acreage after filtering.",
    "This supports the weighting rule.",
    "forest documentation",
    "prose"
  )

  expect_match(
    html,
    "> Canopy cover is always acre-weighted.\n> Report acreage after filtering.",
    fixed = TRUE
  )
})

test_that("citation asides leave trust copy to their markers", {
  html <- citation_aside_html(
    "Canopy cover is always acre-weighted.",
    "This supports the weighting rule.",
    "forest documentation",
    "prose"
  )

  expect_no_match(
    html,
    "Quote matched exactly against trusted context. Explanation generated by AI.",
    fixed = TRUE
  )
})

# A measure the fixture describes: its arguments are all commons-supplied, so
# `arguments` stays empty and every formal is an injected source.
fixture_corpus_measure <- function(spec) {
  injected <- as.character(unlist(spec$injected) %||% character())
  fn <- if (length(injected) == 0) {
    function() NULL
  } else {
    formals <- rep(list(rlang::missing_arg()), length(injected))
    names(formals) <- injected
    rlang::new_function(formals, quote(NULL))
  }
  measure(spec$name, spec$description, fn)
}

test_that("build_citation_corpus matches the shared fixture", {
  cases <- shared_fixture("citation-corpus")$build_citation_corpus$cases
  # An empty fixture would make the loop below vacuously succeed.
  expect_gt(length(cases), 0)

  for (case in cases) {
    layer <- if (is.null(case$docs)) {
      NULL
    } else {
      new_context_layer(as.character(unlist(case$docs)))
    }
    registry <- lapply(case$measures, fixture_corpus_measure)
    sources <- lapply(case$sources, function(spec) {
      dictionary <- if (is.null(spec$dictionary)) {
        NULL
      } else {
        new_data_dictionary(spec$dictionary)
      }
      suppressMessages(data_source(sales = test_sales(), dictionary = dictionary))
    })
    names(sources) <- vapply(case$sources, function(spec) spec$name, character(1))

    corpus <- build_citation_corpus(layer, registry, sources)

    expect_identical(
      lapply(corpus, function(entry) entry[c("label", "kind")]),
      lapply(case$expected, function(entry) entry[c("label", "kind")]),
      info = case$name
    )
    for (want in case$matches) {
      found <- match_citation(want$quote, corpus)
      expect_identical(
        found$label,
        want$label,
        info = paste(case$name, want$quote, sep = ": ")
      )
    }
  }
})


test_that("dataset-level dictionary prose is citable", {
  skip_if_not_installed("yaml")
  path <- withr::local_tempfile(fileext = ".yaml")
  writeLines(
    c(
      '$version: "0.1.0"',
      "name: retail sales",
      "description: Order and revenue data for a small retailer.",
      "details: Revenue figures exclude tax collected at checkout."
    ),
    path
  )
  source <- data_source(sales = test_sales(), dictionary = path)

  corpus <- build_citation_corpus(NULL, list(), list(source))

  expect_equal(
    match_citation(
      "Order and revenue data for a small retailer.",
      corpus
    )$label,
    "data dictionary"
  )
  expect_equal(
    match_citation(
      "Revenue figures exclude tax collected at checkout.",
      corpus
    )$label,
    "data dictionary"
  )
})

# The fixture states a tool result's value as {kind, text} or {kind, parts};
# each package builds and reads back its own content objects from that.
fixture_tool_value <- function(spec) {
  if (identical(spec$kind, "text")) {
    return(spec$text)
  }
  lapply(spec$parts, function(part) ellmer::ContentText(text = part))
}

fixture_value_shape <- function(value) {
  if (is.character(value)) {
    return(list(kind = "text", text = value))
  }
  list(kind = "parts", parts = lapply(value, function(part) part@text))
}

test_that("both packages place the citation request the same way", {
  section <- shared_fixture("citation-request")$requests
  expect_gt(length(section$cases), 0)

  for (case in section$cases) {
    tracker <- new.env(parent = emptyenv())
    tracker$reminder <- section$reminder

    for (step in case$steps) {
      if (identical(step$action, "reset")) {
        tracker$requested <- FALSE
        next
      }
      result <- add_citation_request(
        tool_result(
          fixture_tool_value(step$value),
          title = "Ran SQL",
          tag = "B"
        ),
        tracker
      )
      expect_equal(
        fixture_value_shape(result@value),
        step$expected,
        info = case$name
      )
    }
  }
})

test_that("both packages agree on which turns reset the citation request", {
  section <- shared_fixture("citation-request")$resets
  expect_gt(length(section$cases), 0)

  for (case in section$cases) {
    contents <- lapply(case$contents, function(kind) {
      if (identical(kind, "text")) {
        ellmer::ContentText(text = "a question")
      } else {
        tool_result("6 rows", title = "Ran SQL", tag = "B")
      }
    })

    expect_identical(
      turn_has_user_message(ellmer::Turn("user", contents = contents)),
      case$resets,
      info = case$name
    )
  }
})

test_that("search_context requests a citation for fallback answers", {
  path <- withr::local_tempfile(fileext = ".md")
  writeLines(
    "Regeneration units are tracked separately until they close canopy.",
    path
  )
  agent <- test_agent(context_layer = context_layer(files = path))

  result <- agent_tool(agent, "search_context")(
    query = "regeneration baseline"
  )

  expect_s7_class(result, ellmer::ContentToolResult)
  expect_match(result@value, "<commons-citation>", fixed = TRUE)
})

test_that("citation_reminder_text names the commons-citation dialect", {
  reminder <- citation_reminder_text()

  expect_match(reminder, "<commons-citation>", fixed = TRUE)
  expect_no_match(reminder, "<citation reason", fixed = TRUE)
})

test_that("citation instructions describe only available tool outputs", {
  base <- test_agent()$get_system_prompt()
  expect_match(base, "<commons-citation>", fixed = TRUE)
  expect_match(base, "From `search_context`", fixed = TRUE)
  expect_match(base, "From `describe_table`", fixed = TRUE)
  expect_match(base, "From `run_sql`", fixed = TRUE)
  expect_match(base, "output from `run_r`", fixed = TRUE)
  expect_no_match(base, "`search_pool`", fixed = TRUE)
  expect_no_match(base, "`call_measure`", fixed = TRUE)
  expect_no_match(base, "`call_metrics`", fixed = TRUE)

  with_measures <- test_agent(
    semantic_layer = semantic_layer(count_measure_tool())
  )$get_system_prompt()
  expect_match(with_measures, "From `search_pool`", fixed = TRUE)
  expect_match(with_measures, "Result values from `call_measure`", fixed = TRUE)
  expect_no_match(with_measures, "`call_metrics`", fixed = TRUE)
  expect_no_match(with_measures, "Native semantic-model", fixed = TRUE)
})

test_that("citation trust exception names trusted calculation tools", {
  expect_equal(citation_trust_exception(character()), "")
  expect_equal(
    citation_trust_exception("call_measure"),
    " that is not based solely on output from `call_measure`"
  )
  expect_equal(
    citation_trust_exception("call_calculation"),
    " that is not based solely on output from `call_calculation`"
  )
  expect_equal(
    citation_trust_exception(
      c("search_pool", "call_measure", "call_metrics")
    ),
    paste0(
      " that is not based solely on output from `search_pool`",
      " or `call_measure`",
      " or `call_metrics`"
    )
  )
})

test_that("user messages reset citation requests but tool results do not", {
  agent <- test_agent()
  tracker <- agent$.__enclos_env__$private$citation_request
  tracker$requested <- TRUE

  agent$add_turn(
    ellmer::UserTurn("How many orders are there?"),
    ellmer::AssistantTurn("I'll check."),
    log_tokens = FALSE
  )
  expect_false(tracker$requested)

  tracker$requested <- TRUE
  agent$add_turn(
    ellmer::UserTurn(list(tool_result("6 rows", title = "Ran SQL", tag = "B"))),
    ellmer::AssistantTurn("There are 6 orders."),
    log_tokens = FALSE
  )
  expect_true(tracker$requested)
})

test_that("render_citation_aside emits a labeled aside with source details", {
  corpus <- list(list(
    label = "sales table",
    kind = "schema",
    text = "Revenue is recognized at shipment, not at order placement."
  ))
  out <- render_citation_aside(
    "Revenue is recognized at shipment, not at order placement.",
    "The computation follows the documented recognition rule.",
    corpus
  )
  # The pill renders the uniform quote mark; the per-kind icon and the
  # source label appear in the body title instead.
  expect_match(
    out$html,
    paste0(
      '^<shiny-aside label="sales table" ',
      'icon="',
      commons_icon_url("citation-mark.svg")
    )
  )
  expect_match(
    out$html,
    paste0(
      '<span class="commons-citation-title"><img src="',
      commons_icon_url("citation-schema.svg"),
      '" alt="">'
    ),
    fixed = TRUE
  )
  expect_no_match(out$html, "data:image", fixed = TRUE)
  expect_match(
    out$html,
    "The computation follows the documented recognition rule.",
    fixed = TRUE
  )
  expect_match(out$html, "> Revenue is recognized at shipment", fixed = TRUE)
  expect_no_match(
    out$html,
    "Quote matched exactly against trusted context. Explanation generated by AI.",
    fixed = TRUE
  )
  expect_identical(out$decision$status, "accepted")
})

test_that("render_citation_aside emits nothing for an unverified quote", {
  out <- render_citation_aside("Nobody ever wrote this.", "reason", list())
  expect_identical(out$html, "")
  expect_identical(out$decision$status, "rejected")
})

test_that("unknown citation kinds have no icon", {
  expect_null(citation_icon_url("unknown"))
  expect_null(commons_icon_url("missing.svg"))
})
