test_that("normal package checks can disable browser tests explicitly", {
  withr::local_envvar(COMMONS_SKIP_BROWSER_TESTS = "true")
  expect_condition(
    skip_if_browser_tests_disabled(),
    class = "skip",
    regexp = "Browser tests are disabled"
  )
})

test_that("Shiny Chat renders streamed citations as icon markers", {
  skip_on_cran()
  skip_if_not_installed("shinytest2")
  skip_if_not_installed("chromote")
  skip_if_browser_tests_disabled()
  skip_if_ellmer_streaming_hooks_unavailable()

  app <- shinytest2::AppDriver$new(
    browser_test_app("citation-stream"),
    name = "citation-stream",
    timeout = 30 * 1000,
    load_timeout = 30 * 1000
  )
  withr::defer(app$stop())

  app$wait_for_js(
    "document.body.innerText.includes('After citations.');",
    timeout = 30 * 1000
  )
  marker_selector <- paste0(
    'button.shiny-aside-pill[aria-label="documentation"],',
    'button.shiny-aside-pill[aria-label="sales table"]'
  )
  app$wait_for_js(
    paste0("document.querySelectorAll('", marker_selector, "').length === 2;"),
    timeout = 30 * 1000
  )

  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('",
        marker_selector,
        "'))",
        ".map((node) => node.textContent).join('|');"
      )
    ),
    "documentation|sales table"
  )
  expect_identical(
    app$get_js(
      paste0(
        "(() => {",
        "const style = getComputedStyle(document.querySelector(",
        "'button.shiny-aside-pill[aria-label=\"documentation\"]'));",
        "return [",
        "'--shiny-chat-aside-marker-color',",
        "'--shiny-chat-aside-marker-hover-color',",
        "'--shiny-chat-aside-marker-bg',",
        "'--shiny-chat-aside-marker-hover-bg'",
        "].every((name) => style.getPropertyValue(name).trim() !== '');",
        "})()"
      )
    ),
    TRUE
  )
  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('",
        marker_selector,
        "'))",
        ".map((node) => node.closest('p')?.innerText)",
        ".join('|');"
      )
    ),
    paste(
      "Canopy weighting follows the documentation.",
      "Revenue timing follows the table definition.",
      sep = "|"
    )
  )
  first_marker <- 'button.shiny-aside-pill[aria-label="documentation"]'
  first_dialog <- '[role="dialog"][aria-label="documentation"]'
  app$get_js(
    paste0("document.querySelector('", first_marker, "').click();")
  )
  app$wait_for_js(
    paste0("document.querySelector('", first_dialog, "') !== null;"),
    timeout = 30 * 1000
  )
  first <- app$get_js(
    paste0("document.querySelector('", first_dialog, "').innerText;")
  )
  expect_match(first, "documentation", fixed = TRUE)
  expect_match(first, "Supports the reported weighting.", fixed = TRUE)
  expect_match(
    first,
    "Canopy cover is always acre-weighted for reporting.",
    fixed = TRUE
  )
  expect_no_match(
    first,
    "Quote matched exactly against trusted context. Explanation generated by AI.",
    fixed = TRUE
  )
  expect_identical(
    app$get_js(
      paste0(
        "document.querySelector('",
        first_dialog,
        "')",
        ".querySelector('button[aria-label=\"Next source\"]') === null;"
      )
    ),
    TRUE
  )
  app$get_js(
    paste0(
      "document.dispatchEvent(",
      "new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })",
      ");"
    )
  )
  app$wait_for_js(
    paste0("document.querySelector('", first_dialog, "') === null;"),
    timeout = 30 * 1000
  )

  second_marker <- 'button.shiny-aside-pill[aria-label="sales table"]'
  second_dialog <- '[role="dialog"][aria-label="sales table"]'
  app$get_js(
    paste0("document.querySelector('", second_marker, "').click();")
  )
  app$wait_for_js(
    paste0("document.querySelector('", second_dialog, "') !== null;"),
    timeout = 30 * 1000
  )
  second <- app$get_js(
    paste0("document.querySelector('", second_dialog, "').innerText;")
  )
  expect_match(second, "sales table", fixed = TRUE)
  expect_match(second, "Supports the recognition timing.", fixed = TRUE)
  expect_match(
    second,
    "Revenue is recognized at shipment, not at order placement.",
    fixed = TRUE
  )
  expect_identical(
    app$get_js(
      paste0(
        "document.querySelector('",
        second_dialog,
        "')",
        ".querySelector('img[src$=\"/citation-schema.svg\"]') !== null;"
      )
    ),
    TRUE
  )

  answer <- app$get_js(
    "document.querySelector('.shiny-chat-message')?.innerText;"
  )
  answer_html <- app$get_js(
    "document.querySelector('.shiny-chat-message')?.innerHTML;"
  )
  expect_match(
    answer,
    "Canopy weighting follows the documentation.",
    fixed = TRUE
  )
  expect_match(
    answer,
    "Revenue timing follows the table definition.",
    fixed = TRUE
  )
  expect_match(answer, "After citations.", fixed = TRUE)
  expect_no_match(answer_html, "commons-citation", fixed = TRUE)
})

test_that("Shiny Chat distinguishes verified, cited, and untrusted asides", {
  skip_on_cran()
  skip_if_not_installed("shinytest2")
  skip_if_not_installed("chromote")
  skip_if_browser_tests_disabled()

  app <- shinytest2::AppDriver$new(
    browser_test_app("aside-states"),
    name = "aside-states",
    timeout = 30 * 1000,
    load_timeout = 30 * 1000
  )
  withr::defer(app$stop())

  app$wait_for_js(
    paste0(
      "document.querySelector('button[aria-label=\"Verified answer\"]') && ",
      "document.querySelector(",
      "'button.shiny-aside-pill[aria-label=\"documentation\"]') && ",
      "document.querySelector('button[aria-label=\"Untrusted\"]');"
    ),
    timeout = 30 * 1000
  )

  expect_identical(
    app$get_js(
      paste0(
        "['Verified answer', 'Untrusted']",
        ".map((label) => document.querySelector(",
        "`button[aria-label=\"${label}\"]`",
        ").textContent).join('|');"
      )
    ),
    "Verified answer|Untrusted"
  )
  expect_identical(
    app$get_js(
      paste0(
        "['Verified answer', 'Untrusted']",
        ".map((label) => getComputedStyle(document.querySelector(",
        "`button[aria-label=\"${label}\"]`",
        ")).fontWeight).join('|');"
      )
    ),
    "400|400"
  )
  expect_identical(
    app$get_js(
      paste0(
        "document.querySelector(",
        "'button.shiny-aside-pill[aria-label=\"documentation\"]')",
        ".closest('p')?.innerText.includes('Supported claim.');"
      )
    ),
    TRUE
  )
  expect_identical(
    app$get_js(
      paste0(
        "(() => {",
        "const trusted = document.querySelector(",
        "'button[aria-label=\"Verified answer\"]');",
        "const warning = document.querySelector(",
        "'button[aria-label=\"Untrusted\"]');",
        "return trusted && warning && ",
        "getComputedStyle(trusted).color !== getComputedStyle(warning).color;",
        "})()"
      )
    ),
    TRUE
  )

  app$get_js(
    'document.querySelector(\'button[aria-label="Verified answer"]\').click();'
  )
  verified_dialog <- '[role="dialog"][aria-label="Verified answer"]'
  app$wait_for_js(
    paste0("document.querySelector('", verified_dialog, "') !== null;"),
    timeout = 30 * 1000
  )
  verified <- app$get_js(
    paste0("document.querySelector('", verified_dialog, "').innerText;")
  )
  expect_no_match(verified, "Verified answer", fixed = TRUE)
  expect_no_match(verified, "How answer trust is determined", fixed = TRUE)
  expect_match(
    verified,
    "This answer comes from a trusted calculation.",
    fixed = TRUE
  )
  app$wait_for_js(
    paste0(
      "document.querySelector('",
      verified_dialog,
      " .commons-provenance-info-trigger') !== null;"
    ),
    timeout = 30 * 1000
  )
  expect_true(
    app$get_js(
      paste0(
        "(() => { const control = document.querySelector('",
        verified_dialog,
        " .commons-provenance-info'); return ",
        "control.previousSibling.textContent.endsWith('calculation. ') && ",
        "getComputedStyle(control).display === 'inline-flex'; })()"
      )
    )
  )
  app$get_js(
    paste0(
      "document.querySelector('",
      verified_dialog,
      " .commons-provenance-info-trigger').click();"
    )
  )
  info_modal <- "#commons-provenance-info-modal.show"
  app$wait_for_js(
    paste0(
      "document.querySelector('",
      info_modal,
      "') !== null && ",
      "document.querySelector('.modal-backdrop.show') !== null;"
    ),
    timeout = 30 * 1000
  )
  app$wait_for_js(
    paste0(
      "document.activeElement === document.querySelector('",
      info_modal,
      "');"
    ),
    timeout = 30 * 1000
  )
  expect_false(
    app$get_js(
      paste0(
        "document.querySelector('",
        verified_dialog,
        "').contains(",
        "document.querySelector('",
        info_modal,
        "'));"
      )
    )
  )
  app$get_js(
    paste0(
      "document.querySelector('",
      info_modal,
      " [data-bs-dismiss=\"modal\"]').click();"
    )
  )
  app$wait_for_js(
    paste0("document.querySelector('", info_modal, "') === null;"),
    timeout = 30 * 1000
  )
})

test_that("Shiny Chat preserves Markdown blocks around citations", {
  skip_on_cran()
  skip_if_not_installed("shinytest2")
  skip_if_not_installed("chromote")
  skip_if_browser_tests_disabled()

  app <- shinytest2::AppDriver$new(
    browser_test_app("citation-markdown-blocks"),
    name = "citation-markdown-blocks",
    timeout = 30 * 1000,
    load_timeout = 30 * 1000
  )
  withr::defer(app$stop())

  app$wait_for_js(
    paste0(
      "document.querySelectorAll(",
      "'button.shiny-aside-pill[aria-label=\"documentation\"]')",
      ".length === 2;"
    ),
    timeout = 30 * 1000
  )

  expect_identical(
    app$get_js("document.querySelectorAll('pre code').length;"),
    1L
  )
  expect_identical(
    app$get_js("document.querySelectorAll('table').length;"),
    1L
  )
  expect_identical(
    app$get_js(
      paste0(
        "document.querySelectorAll(",
        "'button.shiny-aside-pill[aria-label=\"documentation\"]')",
        ".length;"
      )
    ),
    2L
  )
  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('pre code'))",
        ".some((node) => node.textContent.includes('shiny-aside'));"
      )
    ),
    FALSE
  )
})
