test_that("normal package checks can disable browser tests explicitly", {
  withr::local_envvar(COMMONS_SKIP_BROWSER_TESTS = "true")
  expect_condition(
    skip_if_browser_tests_disabled(),
    class = "skip",
    regexp = "Browser tests are disabled"
  )
})

test_that("Shiny Chat renders native numbered streamed citations", {
  skip_on_cran()
  skip_if_not_installed("shinytest2")
  skip_if_not_installed("chromote")
  skip_if_browser_tests_disabled()

  app <- shinytest2::AppDriver$new(
    browser_test_app("citation-stream"),
    name = "citation-stream",
    timeout = 30 * 1000,
    load_timeout = 30 * 1000
  )
  withr::defer(app$stop())

  app$wait_for_js(
    "document.body.innerText.includes('After citations.');",
    timeout = 30 * 1000
  )
  app$wait_for_js(
    "document.querySelectorAll('.shiny-aside-pill--number').length === 2;",
    timeout = 30 * 1000
  )

  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('.shiny-aside-pill--number'))",
        ".map((node) => node.textContent).join('|');"
      )
    ),
    "1|2"
  )
  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('.shiny-aside-pill--number'))",
        ".map((node) => node.getAttribute('aria-label')).join('|');"
      )
    ),
    "Aside 1: documentation|Aside 2: sales table"
  )

  markers <- app$get_js(
    "document.querySelectorAll('.shiny-aside-pill--number').length;"
  )
  expect_identical(markers, 2L)
  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('.shiny-aside-pill--number'))",
        ".every((node) => {",
        "const box = node.getBoundingClientRect();",
        "return box.width >= 24 && box.height >= 24;",
        "});"
      )
    ),
    TRUE
  )
  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('.shiny-aside-pill--number'))",
        ".map((node) => node.closest('p')?.innerText)",
        ".join('|');"
      )
    ),
    paste(
      "Canopy weighting follows the documentation.\n1",
      "Revenue timing follows the table definition.\n2",
      sep = "|"
    )
  )
  app$get_js(
    "document.querySelectorAll('.shiny-aside-pill--number')[0].click();"
  )
  app$wait_for_js(
    "document.querySelector('.shiny-aside-popover') !== null;",
    timeout = 30 * 1000
  )
  first <- app$get_js(
    "document.querySelector('.shiny-aside-popover').innerText;"
  )
  expect_match(first, "documentation", fixed = TRUE)
  expect_match(first, "Supports the reported weighting.", fixed = TRUE)
  expect_match(
    first,
    "Canopy cover is always acre-weighted for reporting.",
    fixed = TRUE
  )
  expect_match(
    first,
    "Quote matched exactly against trusted context. Explanation generated by AI.",
    fixed = TRUE
  )
  expect_identical(
    app$get_js(
      "document.querySelector('.shiny-aside-popover__nav') === null;"
    ),
    TRUE
  )
  app$get_js(
    paste0(
      "document.dispatchEvent(",
      "new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })",
      ");"
    )
  )
  app$wait_for_js(
    "document.querySelector('.shiny-aside-popover') === null;",
    timeout = 30 * 1000
  )

  app$get_js(
    "document.querySelectorAll('.shiny-aside-pill--number')[1].click();"
  )
  app$wait_for_js(
    "document.querySelector('.shiny-aside-popover') !== null;",
    timeout = 30 * 1000
  )
  second <- app$get_js(
    "document.querySelector('.shiny-aside-popover').innerText;"
  )
  expect_match(second, "sales table", fixed = TRUE)
  expect_match(second, "Supports the recognition timing.", fixed = TRUE)
  expect_match(
    second,
    "Revenue is recognized at shipment, not at order placement.",
    fixed = TRUE
  )
  expect_identical(
    app$get_js(
      paste0(
        "document.querySelector(",
        "'.shiny-aside-popover__label img[src$=\"/citation-schema.svg\"]'",
        ") !== null;"
      )
    ),
    TRUE
  )

  answer <- app$get_js(
    "document.querySelector('.shiny-chat-message')?.innerText;"
  )
  answer_html <- app$get_js(
    "document.querySelector('.shiny-chat-message')?.innerHTML;"
  )
  expect_match(
    answer,
    "Canopy weighting follows the documentation.",
    fixed = TRUE
  )
  expect_match(
    answer,
    "Revenue timing follows the table definition.",
    fixed = TRUE
  )
  expect_match(answer, "After citations.", fixed = TRUE)
  expect_no_match(answer_html, "commons-citation", fixed = TRUE)
})

test_that("Shiny Chat distinguishes verified, cited, and untrusted asides", {
  skip_on_cran()
  skip_if_not_installed("shinytest2")
  skip_if_not_installed("chromote")
  skip_if_browser_tests_disabled()

  app <- shinytest2::AppDriver$new(
    browser_test_app("aside-states"),
    name = "aside-states",
    timeout = 30 * 1000,
    load_timeout = 30 * 1000
  )
  withr::defer(app$stop())

  app$wait_for_js(
    paste0(
      "document.querySelectorAll('.shiny-aside-pill img').length === 2 && ",
      "document.querySelectorAll('.shiny-aside-pill--number').length === 1;"
    ),
    timeout = 30 * 1000
  )

  labels <- app$get_js(
    paste0(
      "Array.from(document.querySelectorAll('.shiny-aside-pill__label'))",
      ".map((node) => node.textContent).join('|');"
    )
  )
  expect_identical(labels, "Verified answer|Untrusted")
  expect_identical(
    app$get_js(
      "document.querySelector('.shiny-aside-pill--number').getAttribute('aria-label');"
    ),
    "Aside 1: documentation"
  )
  expect_identical(
    app$get_js(
      "getComputedStyle(document.querySelector('.shiny-aside-pill')).fontWeight;"
    ),
    "400"
  )

  expect_identical(
    app$get_js(
      paste0(
        "document.querySelector(",
        "'.shiny-aside-pill--number'",
        ").closest('p')?.innerText.includes('Supported claim.');"
      )
    ),
    TRUE
  )
})

test_that("Shiny Chat preserves Markdown blocks around citations", {
  skip_on_cran()
  skip_if_not_installed("shinytest2")
  skip_if_not_installed("chromote")
  skip_if_browser_tests_disabled()

  app <- shinytest2::AppDriver$new(
    browser_test_app("citation-markdown-blocks"),
    name = "citation-markdown-blocks",
    timeout = 30 * 1000,
    load_timeout = 30 * 1000
  )
  withr::defer(app$stop())

  app$wait_for_js(
    "document.querySelectorAll('.shiny-aside-pill--number').length === 2;",
    timeout = 30 * 1000
  )

  expect_identical(
    app$get_js("document.querySelectorAll('pre code').length;"),
    1L
  )
  expect_identical(
    app$get_js("document.querySelectorAll('table').length;"),
    1L
  )
  expect_identical(
    app$get_js(
      "document.querySelectorAll('.shiny-aside-pill--number').length;"
    ),
    2L
  )
  expect_identical(
    app$get_js(
      paste0(
        "Array.from(document.querySelectorAll('pre code'))",
        ".some((node) => node.textContent.includes('shiny-aside'));"
      )
    ),
    FALSE
  )
})
