"""Render the system prompt from the template shared by both packages."""

from __future__ import annotations

import datetime
import os
import re
from collections.abc import Iterable, Mapping
from importlib.resources import files
from pathlib import Path
from typing import Any

import jinja2

# prompts/ at the repository root is the source; the copy inside the package is
# generated by scripts/sync-shared.sh.
_PROMPTS = files("commons") / "prompts"

_RAW = re.compile(r"\{%\s*raw\s*%\}.*?\{%\s*endraw\s*%\}", re.DOTALL)
_CONDITION = re.compile(r"\{%\s*if\s+(?:not\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*%\}")
_VALUE = re.compile(r"\{\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*\}\}")
_TAG = re.compile(r"\{%.*?%\}", re.DOTALL)
_ANY_VALUE = re.compile(r"\{\{.*?\}\}", re.DOTALL)
_COMMENT_TAG = re.compile(r"\{#.*?#\}", re.DOTALL)
_SUPPORTED_TAG = re.compile(
    r"^(?:if\s+(?:not\s+)?[A-Za-z_][A-Za-z0-9_]*|else|endif|raw|endraw)$"
)
_SUPPORTED_VALUE = re.compile(r"^\{\{\s*[A-Za-z_][A-Za-z0-9_]*\s*\}\}$")
_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
_BLANK_LINES = re.compile(r"\n[ \t]*\n(?:[ \t]*\n)+")

# The trusted-calculation tools, in the order the citation sentence names them,
# and every tool the citable and non-citable lists branch on.
TRUSTED_TOOLS = ("search_pool", "call_measure", "call_metrics", "call_calculation")
CITED_TOOLS = (
    "search_pool",
    "search_context",
    "describe_table",
    "run_sql",
    "call_measure",
    "call_metrics",
    "call_calculation",
    "run_r",
)


def read_prompt(name: str) -> str:
    """Read one of the shared prompt files by file name."""
    return (_PROMPTS / name).read_text(encoding="utf-8").rstrip("\n")


def system_prompt_template() -> str:
    return read_prompt("system-prompt.md")


def render_system_prompt(template: str, data: Mapping[str, Any]) -> str:
    """Render the prompt template against `data`.

    Substituted values are inserted literally and never rendered again, which is
    what lets governed-definition tokens and app-authored instructions contain
    template syntax of their own.
    """
    _check_template_syntax(template)
    _check_template_data(template, data)
    rendered = (
        jinja2.Environment(
            trim_blocks=True,
            lstrip_blocks=True,
            undefined=jinja2.StrictUndefined,
            autoescape=False,
        )
        .from_string(template)
        .render(**data)
    )
    rendered = _COMMENT.sub("", rendered)
    rendered = _BLANK_LINES.sub("\n\n", rendered)
    return rendered.strip()


# Jinja2 is much larger than the subset both packages implement, so a template
# that reaches beyond it is rejected here rather than rendering and then failing
# in R.
def _check_template_syntax(template: str) -> None:
    outside_raw = _RAW.sub("", template)
    unsupported = [
        tag
        for tag in _TAG.findall(outside_raw)
        if not _SUPPORTED_TAG.match(tag.removeprefix("{%").removesuffix("%}").strip())
    ]
    unsupported += [
        value
        for value in _ANY_VALUE.findall(outside_raw)
        if not _SUPPORTED_VALUE.match(value)
    ]
    unsupported += _COMMENT_TAG.findall(outside_raw)
    if unsupported:
        raise ValueError(
            f"Unsupported prompt template syntax {unsupported[0]}. Templates are "
            "shared with the R package, which renders the same subset: "
            "{{ name }}, {% if name %}, {% if not name %}, {% else %}, "
            "{% endif %}, and {% raw %}."
        )


# Jinja2 would accept a string where a flag belongs and quietly branch on
# whether it is empty. The R renderer rejects that, so reject it here too:
# a template that renders in one package has to render in the other.
def _check_template_data(template: str, data: Mapping[str, Any]) -> None:
    outside_raw = _RAW.sub("", template)
    for name in _CONDITION.findall(outside_raw):
        value = _template_value(name, data)
        if not isinstance(value, bool):
            raise TypeError(
                f"Prompt template condition {name!r} must be True or False."
            )
    for name in _VALUE.findall(outside_raw):
        value = _template_value(name, data)
        if not isinstance(value, str):
            raise TypeError(f"Prompt template value {name!r} must be a string.")


def _template_value(name: str, data: Mapping[str, Any]) -> Any:
    if name not in data:
        raise ValueError(f"Prompt template refers to {name!r}, which has no value.")
    return data[name]


def tool_availability(tools: Iterable[str]) -> dict[str, bool]:
    """One flag per tool the citation sections name."""
    registered = set(tools)
    return {f"has_{tool}": tool in registered for tool in CITED_TOOLS}


def citation_trust_exception(tools: Iterable[str]) -> str:
    """The clause naming the tools whose output is trusted on its own.

    It is spliced into a sentence, so it carries its own leading space and is
    empty when the agent registered no trusted-calculation tool.
    """
    registered = set(tools)
    trusted = [tool for tool in TRUSTED_TOOLS if tool in registered]
    if not trusted:
        return ""
    named = " or ".join(f"`{tool}`" for tool in trusted)
    return f" that is not based solely on output from {named}"


def prompt_date() -> str:
    """Today's date where the agent runs, matching the R package's local date."""
    return datetime.datetime.now().astimezone().date().isoformat()


_CLAUDE_5 = re.compile(r"(^|[./:_-])claude-[^-]+-5($|[./:@_-])")


def is_claude_5_model(model: str | None) -> bool:
    """Whether a model id names a Claude 5 model, whatever the provider."""
    if not isinstance(model, str):
        return False
    return _CLAUDE_5.search(model.lower()) is not None


_INSTRUCTION_EXTENSIONS = ("md", "rmd", "txt", "prompt")


def check_instructions(instructions: str | None) -> None:
    """Fail when instructions name a file that is not there.

    Instructions are either the text itself or a path to it, so a mistyped path
    would otherwise reach the model as its own instruction.
    """
    if instructions is None:
        return
    if _looks_like_path(instructions) and not Path(instructions).is_file():
        raise FileNotFoundError(f"Instructions file {instructions} does not exist.")


def read_instructions(instructions: str | None) -> str | None:
    if instructions is None:
        return None
    path = Path(instructions)
    if path.is_file():
        return path.read_text(encoding="utf-8").rstrip("\n")
    return instructions


def _looks_like_path(instructions: str) -> bool:
    if "\n" in instructions:
        return False
    extension = os.path.splitext(instructions)[1].lstrip(".").lower()
    return (
        "/" in instructions
        or "\\" in instructions
        or extension in _INSTRUCTION_EXTENSIONS
        or (bool(extension) and not re.search(r"\s", instructions))
    )
