#!/usr/bin/env bash
# Copy the repository's shared sources into the packages that ship or read them.
#
# Neither an R package nor a Python wheel can reach a file outside its own
# directory: inst/ contents must exist at install time, testthat needs its
# fixtures inside the package, and wheel data must sit under the package root.
# So sharing means copying. The copies are committed, this script generates
# them, and CI re-runs the script and fails when a copy is stale. A hand-edited
# copy is a defect.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# One line per shared source: the source directory, then every destination.
# The Python suite reads tests/shared/ in place, so only the R package needs
# that copy; both packages ship the prompts and the browser assets. Nothing
# in pkg-py reads www/ until its UI layer lands, but the destination belongs
# with the move rather than with the first reader.
sources=(
  "tests/shared pkg-r/tests/testthat/fixtures/shared"
  "prompts pkg-r/inst/prompts pkg-py/src/commons/prompts"
  "www pkg-r/inst/www pkg-py/src/commons/www"
)

for entry in "${sources[@]}"; do
  read -r src dests <<<"$entry"

  # Every file, whatever its extension: a fixture may use a format other than
  # JSON, and globbing would drop such a file silently while leaving the
  # staleness check green. READMEs document the source, so they are the one
  # exclusion; each destination gets a generated one instead.
  files="$(cd "$root/$src" && find . -type f ! -name README.md | sed 's|^\./||' | sort)"
  if [ -z "$files" ]; then
    echo "No files found in $src" >&2
    exit 1
  fi

  for dest in $dests; do
    # Regenerate rather than overwrite, so a file deleted from the source also
    # disappears from the copy.
    rm -rf "${root:?}/$dest"
    mkdir -p "$root/$dest"
    printf '%s\n' "$files" | while IFS= read -r rel; do
      mkdir -p "$root/$dest/$(dirname "$rel")"
      cp "$root/$src/$rel" "$root/$dest/$rel"
    done

    cat >"$root/$dest/README.md" <<EOM
Generated by \`scripts/sync-shared.sh\`. Do not edit anything in this directory. Edit \`$src/\` at the repository root and re-run the script.
EOM

    count="$(printf '%s\n' "$files" | wc -l | tr -d ' ')"
    echo "Synced ${count} file(s) from ${src}/ into ${dest}/"
  done
done
