#!/usr/bin/env bash
# Copy the cross-language fixtures in tests/shared/ into the R package.
#
# The Python suite reads tests/shared/ in place. The R suite cannot: testthat
# needs its fixtures inside the package, and an installed package cannot reach
# the repository root. So the R side reads a committed copy, this script
# generates it, and CI re-runs the script and fails when the copy is stale.
# A hand-edited copy is a defect.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/tests/shared"
dest="$root/pkg-r/tests/testthat/fixtures/shared"

# Every file, whatever its extension: the source README permits a fixture to use
# a format other than JSON, and globbing *.json would drop such a file silently
# while leaving the staleness check green. The source README is documentation
# rather than a fixture, so it is the one exclusion.
fixtures="$(cd "$src" && find . -type f ! -name README.md | sed 's|^\./||' | sort)"
if [ -z "$fixtures" ]; then
  echo "No fixtures found in $src" >&2
  exit 1
fi

# Regenerate rather than overwrite, so a fixture deleted from the source also
# disappears from the copy.
rm -rf "$dest"
mkdir -p "$dest"
printf '%s\n' "$fixtures" | while IFS= read -r rel; do
  mkdir -p "$dest/$(dirname "$rel")"
  cp "$src/$rel" "$dest/$rel"
done

cat >"$dest/README.md" <<'EOF'
Generated by `scripts/sync-shared-fixtures.sh`. Do not edit anything in this directory. Edit `tests/shared/` at the repository root and re-run the script.
EOF

count="$(printf '%s\n' "$fixtures" | wc -l | tr -d ' ')"
echo "Synced ${count} fixture(s) into ${dest#"$root"/}"
